giantswarm/microkit

command/daemon/command.go
command/daemon/flag.go

This was recently added to Kubernetesd. We want to have this support here for all microservices.

added support for multiple config files

---

server/server.go

This PR adds general access logging.

added general access logging

---

server/server.go

This PR adds unified error responses and error logging to all microkit microservices.

wrapped custom error encoder

---

logger/logger.go

This PR addresses the configuration of the io.Writer. By default the logger does not print to stdout. Logs will simply be discarded. This is to make default loggers not print anything during unit testing. As soon as applications want to log messages of microservices, the logger has to be configured with os.Stdout accordingly.

configure logger io writer and default to ioutil.Discard

---

server/error.go
server/metrics.go
server/server.go

This PR adds metrics about error counts. WDYT?
RFR @giantswarm/team-positive

added metrics for error counts

---

storage/etcd/README.md
storage/etcd/service.go
storage/etcdv2/README.md
storage/etcdv2/error.go
storage/etcdv2/service.go
storage/etcdv2/service_test.go
storage/storage.go

This PR is to support legacy micro services which still have to use etcd v2.

added etcd v2 storage implementation

---

command/daemon/command.go
server/server.go
server/spec.go

This PR provides some improvements around logging and instrumentation. This aims to help analyzing problems with microservices using microkit.

provide not found handler

---

storage/etcd/service.go
storage/etcd/service_integration_test.go
storage/etcdv2/service.go
storage/etcdv2/service_integration_test.go
storage/memory/service.go
storage/memory/service_test.go
storage/spec.go

This PR goes towards https://github.com/giantswarm/giantswarm/issues/1123.

added context to storage packages

---

server/server.go

This PR is for some boyscouting. It intends to do the server endpoint initialization in a more readable way.

refactored server endpoint initialization

---

server/server.go
server/server_test.go

This PR goes towards https://github.com/giantswarm/api/issues/292.

provide configurable HTTP handler wrapper for micro server

---

server/codes.go

for planned deletions that are not finished yet
See slack discussion https://gigantic.slack.com/archives/api/p1488807583523044

Adding RESOURCE_DELETION_STARTED code

---

server/codes.go
validator/helpers.go
validator/helpers_test.go
validator/immutable_attribute.go
validator/immutable_attribute_test.go
validator/unknown_attribute.go
validator/unknown_attribute_test.go

Adds a validator for checking if there are any attributes in a request struct that are immutable. WIP

Immutable attribute validator

---

server/codes.go

Helps me achieve the spec for addin/removing members from organizations:
https://github.com/giantswarm/api-spec/pull/32

Add invalid input error code

---

transaction/executer_test.go

- make table tests for testing result
- remove irrelevant assertions

transaction: improve executer tests

---

command/daemon/command.go
server/server.go
server/server_test.go
server/transaction_test.go

Override server factory config only if it has empty value

Check before overwriting server config

---

server/server.go

We introduced a regression in https://github.com/giantswarm/microkit/pull/105 and lost middleware support completely. This only got noticed when updating the api with the latest vendor deps. This PR should fix this problem by bringing back the endpoint wrapper in which we actually make use of the middlewares.

adds back endpoint wrapping for middleware support

---

command/daemon/command.go

Remove masking for `SIGKILL`  since program cannot catch that. From
**signal(7)**:
> The signals **SIGKILL** and **SIGSTOP** cannot be caught, blocked, or ignored.
Add masking for `SIGTERM` to take a chance for graceful shutdown of HTTP
server and return of successful exist status.
Add missing `wg.Wait()`.

Improve signal handling

---

.circleci/config.yml
CHANGELOG.md
command/daemon/command.go
server/server.go

use architect orb

---

CHANGELOG.md
server/codes.go

Towards https://github.com/giantswarm/api-spec/pull/200.

add NOT_YET_AVAILABLE code

---

.github/workflows/zz_generated.create_release.yaml
.github/workflows/zz_generated.create_release_pr.yaml

Add release automation

---

CHANGELOG.md

Fix heading for 0.2.2 changelog entry

---

CHANGELOG.md
go.mod
go.sum

Towards: https://github.com/giantswarm/giantswarm/issues/20186

upgrade github.com/giantswarm/versionbundle v0.3.0 to v1.0.0

---

server/server.go
tls/tls.go

Closes https://github.com/giantswarm/giantswarm/issues/33082

Adapt for golangci-lint v2
