giantswarm/microkit

command/command.go
command/daemon/command.go
command/daemon/error.go
command/daemon/flag.go
command/error.go
command/version/command.go
command/version/error.go
error/error.go
logger/error.go
logger/logger.go
server/error.go
server/response_writer.go
server/server.go

As discussed I introduced a separate error package to prevent some copy/paste code. I am somehow not amazed by this as the benefit of less code is shadowed by additional imports with weird namings and longer lines where the error package methods are used. What do you think? Note that the build fails because https://github.com/giantswarm/microkit/pull/7 is not merged.

Simplify error package

---

command/daemon/command.go

This PR aligns the default port with the port used in our Kubernetes environments. Having a little bit more of consistency in here makes it more easy to switch between development and production. 
RFR @giantswarm/team-positive

set default port to 8000

---

command/daemon/command.go
server/server.go

This PR removes the extra wrapping of the logger inside microkit packages. The wrapping causes a weird behaviour of the caller. I anyway wanted to remove the wrapping because the additionally annotated information did not make that much sense, especially not in case the caller works correctly. 
This is the current faulty behaviour. The caller of the first line is correct. The caller of the second is not. We do not emit any logs inside the go-kit package. 
```
{"caller":"github.com/giantswarm/kubernetesd/service/service.go:96","debug":"creating out-cluster config","time":"16-12-16 21:50:24.542"}
{"caller":"github.com/giantswarm/kubernetesd/vendor/github.com/go-kit/kit/log/log.go:86","code":200,"endpoint":"version","method":"get","package":"command/daemon","path":"/","time":"16-12-16 …
```

removed extra logger wrapper to fix caller

---

command/command.go
command/version/command.go

This PR removes support for the semver project version. The guideline is to apply semver versioning on libraries, not on deployable microservices. We want establish to automatically move forward using CI/CD. Semver versioning has to be applied to packages and APIs, if any. 
RFR @giantswarm/team-positive

removed project version support

---

storage/etcd/service.go

This PR adds the ability to create an etcd storage service being configured with a custom key prefix. This can be useful when different service packages within the same microservice have to deal with storage.
RFR @giantswarm/team-positive

added etcd storage prefix

---

server/error.go
server/server.go

Currently all error responses are written using a plain/text HTTP header. This PR fixes this.

fixed trailing headers for error responses

---

server/codes.go

This PR is to provide general server codes. We need that to fulfil our API specifications. We want to provide response codes and responses messages. These should be the same across our microservices. Note that this is not a complete list and will be modified over time.

provide general server codes

---

server/response_error.go
server/spec.go

This PR is to expose the actually underlying error so it can be accessed within the client's configured error encoder.

expose underlying error for error encoders

---

server/error.go
server/server.go
server/server_test.go
server/transaction.go
server/transaction_test.go

This PR goes towards https://github.com/giantswarm/giantswarm/issues/1123.

validate transaction ID format

---

command/daemon/command.go
server/server.go
server/server_test.go
server/spec.go

This PR eases the client's necessary interface implementations. My next step is to add TLS configuration to the micro server. See also https://github.com/giantswarm/microkit-example/pull/17 where the change is used.

cleaned server interface by providing config method

---

command/daemon/command.go
command/daemon/flag.go
server/server.go

This PR introduces the ability to run HTTPS servers. The usual HTTP server still works. 
```
$ ./microkit-example daemon --server.listen.address=http://127.0.0.1:8000
{"caller":"github.com/giantswarm/microkit-example/vendor/github.com/giantswarm/microkit/server/server.go:297","debug":"running HTTP server","time":"17-02-13 18:29:59.643"}
```
We can now also make the server serve HTTPS with a TLS config as provided by the flags. The cool thing is the flags are built in and we can configure our K8S configmaps quite nicely. 
```
./microkit-example daemon -h
Execute the daemon of the microservice.
Usage:
microkit-example daemon [flags]
Flags:
--config.dirs stringSlice        List of config file directories. (default [.])
--config.files stringSlice       List of the config file names. All viper …
```

support TLS in micro server

---

command/command.go
command/daemon/command.go
command/daemon/spec.go
flag/flag.go
flag/flag_test.go

In Kubernetesd I noticed that flag defaults had not be propagated. This bug was introduced by me in the recent update of the configuration management. Here I provide a fix plus tests. See also https://github.com/giantswarm/kubernetesd/pull/71 where I tested the result manually.

fix default flags and flag initialization

---

storage/etcd/service.go

`etcdv2` is for v2, so it's not quite intuitive that `etcd` is for v3 (and not v1)

etcd version clarification

---

server/codes.go
server/response_writer.go
server/server.go
server/spec.go

This PR provides a way to write a customized response body inside the custom error handler. The default response body will be written if there is no body written before.

write default response body in error encoder if not already written

---

server/server.go
server/transaction.go

As we are renaming the concept of "transactions" to "idempotency" to avoid confusion with the ACID term, we change the HTTP header used for this as well here.
Before: `X-Transaction-ID`
After: `X-Idempotency-Key`

Renaming transaction ID header to X-Idempotency-Key

---

command/daemon/command.go
command/daemon/flag/server/log/log.go
command/daemon/flag/server/server.go
server/server.go

Fixes https://github.com/giantswarm/giantswarm/issues/1825.
There is now an additional flag. Access logging is now disabled by default. See https://github.com/giantswarm/kvm-operator/pull/176. 
```
$ kvm-operator daemon -h
Execute the daemon of the microservice.
Usage:
kvm-operator daemon [flags]
Flags:
--config.dirs strings                     List of config file directories. (default [.])
--config.files strings                    List of the config file names. All viper supported extensions can be used. (default [config])
-h, --help                                    help for daemon
--server.listen.address string            Address used to make the server listen to. (default "http://127.0.0.1:8000")
--server.log.access                       Whether to emit logs for each requested route. …
```

added flag to cofnigure access logging, disabled by default

---

server/codes.go

Towards: https://github.com/giantswarm/giantswarm/issues/2173
We can then let clients know that the reason their attemtps are failing are due to request throttling.
This lets us give some feedback to the user and a better overall UX.
Adding this code was debatable so consider this also a place to debate.

Add too many requests code.

---

server/codes.go

Will let our auth token endpoint be more specific about why a login attempt failed in the case that the user account is expired.

Add account expired code.

---

command/daemon/command.go
command/daemon/flag/server/listen/listen.go
server/server.go

This is my attempt at allowing the prometheus metrics endpoint to be available at a different port than the rest of the microservice.

Add an optional flag that spawns a seperate server for the metrics endpoint

---

command/daemon/command.go
command/daemon/flag/server/enable/debug/debug.go
command/daemon/flag/server/enable/enable.go
command/daemon/flag/server/server.go
server/server.go

This change adds option to enable `net/http/pprof` debug server for localhost.
By enabling this in our services, we can debug performance issues on-demand.
Towards https://github.com/giantswarm/giantswarm/issues/4063

Add option to enable debug server in http://127.0.0.1:6060/debug

---

validator/unknown_attribute.go
validator/unknown_attribute_test.go

This will let me validate the more complex structures, for example:
```
{
"spec": { 
"version":"1.0.0"
}
}
```
This helps us let users know when they provide attributes in their JSON body that aren't actually editable.
For example, if they provide a "spec.name" field, then I want to throw an UnknownAttribute error. With the current implementation that's not possible, since it doesn't check further than `spec`.

Add deep validation for unknown attributes.

---

command/command.go
command/version/command.go

Towards: giantswarm/giantswarm#6559
Exposes version in version command.
/!\ This is a breaking change as it will requires to provide `Version` when creating a new version command.

Exposes version

---

CHANGELOG.md
command/version/command.go
go.mod

Signed-off-by: Matias Charriere <matias@giantswarm.io>
https://github.com/giantswarm/giantswarm/issues/34274

Replace gopkg.in/yaml.v3 with go.yaml.in/yaml/v3
